version: "3.7"

services:
    linkaja-container: 
        container_name: linkaja-container
        image: michaelahli/linkaja:beta
        ports: 
            - 8080:8080
        environment: 
            - SERVER_PORT=8080
            - MONGO_DB=LinkAja
            - MONGO_URI=mongodb://localhost:27017/
            - CORS_HEADER=x-api-key,Authorization,Content-Type,Origin,Accept,Access-Control-Allow-Headers,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin
            - CORS_METHOD=GET,PUT,POST,DELETE
            - CORS_ORIGIN='*'